apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: private-alb
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/subnets: {{ .Values.alb_ingress.private_subnet1 }} , {{ .Values.alb_ingress.private_subnet2 }}, #{{ .Values.alb_ingress.private_subnet3 }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.alb_ingress.certificate_arn }}
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/inbound-cidrs: 0.0.0.0/0 #TODO Replace with Security Group
    alb.ingress.kubernetes.io/healthcheck-path: /
  labels:
    app: private-ingress
spec:
  rules:
  - http:
      paths:
       - path: /*
         backend:
           serviceName: ssl-redirect
           servicePort: use-annotation
  - host: helloworld-django.{{ .Values.domain_name }}
    http:
      paths:
        - backend:
            serviceName: {{ $.Values.env }}-{{ $.Values.project }}-{{ index .Values "djangomodules" "helloworld-django" "name" }}
            servicePort: {{ index .Values "djangomodules" "helloworld-django" "servicePort" }}
           
