{{/*{{- range .Values.djangomodules }}*/}}
{{/*---*/}}
{{/*kind: Secret*/}}
{{/*apiVersion: v1*/}}
{{/*metadata:*/}}
{{/*  name: {{ $.Values.env }}-{{ $.Values.project}}-{{ .name }}*/}}
{{/*type: Opaque*/}}
{{/*stringData:*/}}
{{/*  DEBUG: "true"*/}}
{{/*  SECRET_KEY: {{ quote .secret_key }}*/}}
{{/*  POSTGRES_DB: {{ .dbname }}*/}}
{{/*  POSTGRES_USER: {{ .dbuser }}*/}}
{{/*  POSTGRES_PASSWORD: {{ .dbpass }}*/}}
{{/*  POSTGRES_HOST: {{ .dbhost }}*/}}
{{/*  POSTGRES_PORT: {{ .dbport }}*/}}
{{/*---*/}}
{{/*  {{- end}}*/}}
