---

- name: Build Artifacts
  shell: "mvn clean install"
  args:
    chdir: "../{{ helloworldMW }}"
  register: mvn_result

- name: "mvn clean task output"
  debug:
    var: mvn_result

- name: Create Docker Docker Image Build Directory
  file:
    path: "{{ workspace }}/ansible_managed_{{ env }}/docker_build/{{ item }}"
    state: directory
    mode: '0755'
  with_items: "{{ modules }}"

- name: Copy Artifacts for Docker Image Build
  copy:
    src:  "{{ workspace }}/{{ helloworldMW }}/{{ item }}/target/{{ item }}-0.0.1-SNAPSHOT.war"
    dest: "{{ workspace }}/ansible_managed_{{ env }}/docker_build/{{ item }}/{{ item }}.war"
    state: present
  with_items: "{{ modules }}"
