apiVersion: v1
kind: Service
metadata:
  name: sit-helloworld-django
spec:
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  type: NodePort
  selector:
    app: sit-helloworld-django