apiVersion: v1
kind: Service
metadata:
  name: sit-helloworld-spring
spec:
  ports:
    - port: 8090
      targetPort: 8090
      protocol: TCP
  type: NodePort
  selector:
    app: sit-helloworld-spring
