---

- name: Create Docker Docker Image Build Directory
  file:
    path: "{{ workspace }}/ansible_managed_{{ env }}/docker_build/{{ module }}"
    state: directory
    mode: '0755'

- name: Copy Artifacts for Docker Image Build
  copy:
    src:  "{{ workspace }}/{{ helloworldMW }}/{{ module }}/target/{{ module }}-0.0.1-SNAPSHOT.jar"
    dest: "{{ workspace }}/ansible_managed_{{ env }}/docker_build/{{ module }}/{{ module }}.jar"
    mode: '0755'





