kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: generic
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  zones: ap-southeast-1a
  iopsPerGB: "10"
  fsType: ext4

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slow
  labels:
    app: sit-helloworld-django
spec:
  storageClassName: generic
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
