kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: sit-helloworld-postgres
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
reclaimPolicy: Delete
allowVolumeExpansion: true
mountOptions:
  - debug
  ​
---
  ​
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sit-helloworld-postgres
  labels:
    app: sit-helloworld-django
spec:
  storageClassName: sit-helloworld-postgres
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi