apiVersion: apps/v1
kind: Deployment
metadata:
  name: sit-helloworld-go
  labels:
    app: sit-helloworld-go
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sit-helloworld-go
  template:
    metadata:
      labels:
        app: sit-helloworld-go
    spec:
      containers:
        - name: sit-helloworld-go
          image: 354285753755.dkr.ecr.ap-southeast-1.amazonaws.com/sit-helloworld-go:1
          ports:
            - containerPort: 8888
