apiVersion: apps/v1
kind: Deployment
metadata:
  name: sit-helloworld-spring
  labels:
    app: sit-helloworld-spring
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sit-helloworld-spring
  template:
    metadata:
      labels:
        app: sit-helloworld-spring
    spec:
      containers:
        - name: sit-helloworld-spring
          image: 354285753755.dkr.ecr.ap-southeast-1.amazonaws.com/sit-helloworld-spring:1
          ports:
            - containerPort: 8090
