---
- name: ECR Login
  shell: "$(aws ecr get-login --region {{ aws_region }} --no-include-email)"
  args:
    executable: /bin/bash

- name: Generate Image Tag
  shell: git log --format="%H" -n 1
  args:
    chdir: "{{ workspace }}/{{ helloworldMW }}"
  register: code_commit_id
- debug: var=code_commit_id.stdout_lines

- name: Create Docker Build DIR
  file:
    path: "{{ workspace }}/ansible_managed_{{ env }}/docker_build/{{ module }}"
    state: directory
    mode: '0755'

- name: Generate Dockerfile
  template:
    src: docker-file.j2
    dest: "{{ workspace }}/ansible_managed_{{ env }}/docker_build/{{ module }}/Dockerfile"
  when:
    - module == "frontend" or
      module == "backend"

#    trim_blocks: yes

- name: Build Docker Image
  docker_image:
    build:
      path: "{{ workspace }}/ansible_managed_{{ env }}/docker_build/{{ module }}"
    name: "{{ aws_account_id }}.dkr.ecr.{{ aws_region }}.amazonaws.com/{{ env }}-{{ project_name }}-{{ module }}:local"
    push: no
    state: present
    source: build
  notify:
    - Tag Image and Push to ECR [GIT COMMIT HASH]
    - Tag Image and Push to ECR [LATEST]