aws_account_id: "354285753755"
region: ap-southeast-1
project: helloworld
env: sit
domain_name: helloworld.labs.bka.sh

alb_ingress:
  replicas: 2
  namespace: kube-system
  private_security_group: sg-054362752a65c1785
  public_security_group: sg-0fc7004060169b129
  certificate_arn: arn:aws:acm:ap-southeast-1:956857916952:certificate/c85abb34-1331-4392-a979-7e4023215290
  private_subnet1: subnet-59c0dd1f
  private_subnet2: subnet-7369383a
  public_subnet1: subnet-4978670f
  public_subnet2: subnet-bf092df6
  inbound_cidr: 10.10.0.0/16

version: 0.0.1

modules:
  backend:
    name: backend
    replicas: 2
    maxreplicas: 20
    containerPort: 8010
    servicePort: 8010
    serviceType: NodePort
    requests_memory: 1024Mi
    requests_cpu: 500m
    limit_memory: 4096Mi
    limit_cpu: 1000m

  frontend:
    name: frontend
    replicas: 2
    maxreplicas: 20
    containerPort: 8020
    servicePort: 8020
    serviceType: NodePort
    requests_memory: 1024Mi
    requests_cpu: 500m
    limit_memory: 4096Mi
    limit_cpu: 1000m

